services:
  - type: static
    name: edupilot-web
    env: static
    branch: master
    buildCommand: ""
    staticPublishPath: build/web

  - type: web
    name: edupilot-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate accounts zero
      python manage.py migrate accounts
    startCommand: "gunicorn edupilot_web_backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: e67t3&)wwf1gjx4y82z_%-o6_ppg+$^)(&w9jmj(bggjyd35!$
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: edupilot-backend-f5sa.onrender.com
      - key: DATABASE_URL
        value: postgresql://edupilot_postsqlt_user:H5P8DL6vHyJ7DPuro2cNOl9s7DI4ZVal@dpg-d27uraogjchc738nqf0g-a.oregon-postgres.render.com/edupilot_postsqlt